### ISSUE TITLE
Заменить Adminer на PHPMyAdmin

### ISSUE THREAD

**Issue by webnetkz** [bitrixdock/bitrixdock#220]
Доброго времени суток, пожелание заменить Adminer на PHPMyAdmin.

**Comment by FelemixX** [comment]
```
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
  links:
    - db:db
  ports:
    - '${INTERFACE}:8080:80'
  environment:
    UPLOAD: 1024M # upload_max_filesize, post_max_size
    TZ: Europe/Moscow
    PMA_HOST: mysql
    PMA_ARBITRARY: 1
  restart: on-failure
  stdin_open: true
  tty: true
  networks:
    - bitrixdock
```
