### ISSUE TITLE
Mysql 5.7 уходит в бесконечный рестарт

### ISSUE THREAD

**Issue by dudin-github** [bitrixdock/bitrixdock#57]
После запуска `docker-compose up` бесконечно пытается запуститься mysql с ошибкой:

> [ERROR] --initialize specified but the data directory has files in it. Aborting.

Так происходит с mysql >= 5.7, если поменять mysql/Dockerfile версию на 5.6, то все пройдет нормально. Еще одним вариантом решения стал переход на mariadb в docker-compose.yml:

```
mysql:
        image: mariadb
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - bitrix
        restart: always
```
Но это все полумеры, хотелось бы иметь нормальное решение "из коробки"
