### ISSUE TITLE
Ошибка работы с сокетами

### ISSUE THREAD

**Issue by 6apxat** [bitrixdock/bitrixdock#94]
Установлено и запускается под Windows 10 внутри WSL 2.

```
2020-Jun-24 16:03:35 Работа с сокетами (check_socket): Fail
Connection to localhost:80	Fail
Socket error [111]: Connection refused
```

**Comment by 6apxat** [comment]
Опытным путем выяснилось, что необходимо сделать проброс хоста web_server в контейнер php

`
    php:
        build: ./${PHP_VERSION}
        container_name: php
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:9000:9000'
        links:
            - db
            - memcached
        networks:
            - bitrix
        restart: always
        extra_hosts:
            - "bxtest.ru:10.100.0.5"
`

Осталось понять, как динамически подставлять выданный контейнеру web_server IP.

**Comment by vmpartner** [comment]
127.0.0.1 может подойдет?

**Comment by ReWiG** [comment]
localhost не подходит, каждый раз при запуске подпихивать новый IP тоже не вариант. Может быть существует переменная, которая содержит в себе IP?

**Comment by vmpartner** [comment]
Не удалось найти решение?

**Comment by paskal** [comment]
Я думаю, что знаю, как это поправить. В текущем docker-compose неоправданно сложная настройка сети, я знаю, как сделать её проще, и потенциально это позволить починить описанную проблему.

**Comment by vmpartner** [comment]
Может пора перевести под k8s? )

**Comment by sergiochoo** [comment]
в секции сети контейнера nginx задать статический внутренний IP:
        networks:
          mysite:
            ipv4_address: 10.100.0.60

в секции extra_hosts контейнера php добавить
        extra_hosts:
            - "imya_vashego_saita.ru:10.100.0.60"

**Comment by phasotron** [comment]
> в секции сети контейнера nginx задать статический внутренний IP:
> networks:
> mysite:
> ipv4_address: 10.100.0.60
> 
> в секции extra_hosts контейнера php добавить
> extra_hosts:
> - "imya_vashego_saita.ru:10.100.0.60"

Спасибо, помогло

```
services:
    php:
        extra_hosts:
            - "bitrix.local.cc:10.100.0.66"
    web_server:
        networks:
            bitrix:
                ipv4_address: "10.100.0.66"
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
```
